// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintCalc.Infrastructure.Persistence;

#nullable disable

namespace PrintCalc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409075958_CalculationModelingToggle")]
    partial class CalculationModelingToggle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PrintCalc.Core.Entities.AppSettingsRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrawingPdfPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ElectricityPricePerKwh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EnergyCost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilamentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeModelDesign")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarginPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaterialGrams")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ModelDesignCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ModelDesignHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ModelDesignHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrintCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrintHours")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrintModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceModelPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartFeeCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWithMargin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FilamentTypeId");

                    b.HasIndex("PrintModelId");

                    b.HasIndex("PrinterId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.FilamentStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilamentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InitialWeightKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PurchasePricePerKg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingWeightKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilamentTypeId");

                    b.ToTable("FilamentStocks");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.FilamentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePricePerKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DensityGPerCm3")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiameterMm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TempMaxC")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TempMinC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FilamentTypes");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuoteId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.PrintModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedMaterialGrams")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedPrintHours")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrintModels");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KwhPerHour")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxVolumeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartFeePerPrint")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.PrinterFilamentType", b =>
                {
                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilamentTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrinterId", "FilamentTypeId");

                    b.HasIndex("FilamentTypeId");

                    b.ToTable("PrinterFilamentTypes");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceCalculationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SourceCalculationId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.QuoteLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteLines");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DeltaKg")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilamentStockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilamentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPricePerKg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilamentStockId");

                    b.HasIndex("FilamentTypeId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Calculation", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.Customer", "Customer")
                        .WithMany("Calculations")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PrintCalc.Core.Entities.FilamentType", "FilamentType")
                        .WithMany()
                        .HasForeignKey("FilamentTypeId");

                    b.HasOne("PrintCalc.Core.Entities.PrintModel", "PrintModel")
                        .WithMany()
                        .HasForeignKey("PrintModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PrintCalc.Core.Entities.Printer", "Printer")
                        .WithMany("Calculations")
                        .HasForeignKey("PrinterId");

                    b.Navigation("Customer");

                    b.Navigation("FilamentType");

                    b.Navigation("PrintModel");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.FilamentStock", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.FilamentType", "FilamentType")
                        .WithMany("Stocks")
                        .HasForeignKey("FilamentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilamentType");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Invoice", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintCalc.Core.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.InvoiceLine", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Order", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintCalc.Core.Entities.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.OrderLine", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.PrinterFilamentType", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.FilamentType", "FilamentType")
                        .WithMany("PrinterLinks")
                        .HasForeignKey("FilamentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintCalc.Core.Entities.Printer", "Printer")
                        .WithMany("SupportedFilaments")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilamentType");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Quote", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.Customer", "Customer")
                        .WithMany("Quotes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintCalc.Core.Entities.Calculation", "SourceCalculation")
                        .WithMany()
                        .HasForeignKey("SourceCalculationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("SourceCalculation");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.QuoteLine", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.Quote", "Quote")
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.StockMovement", b =>
                {
                    b.HasOne("PrintCalc.Core.Entities.FilamentStock", "FilamentStock")
                        .WithMany()
                        .HasForeignKey("FilamentStockId");

                    b.HasOne("PrintCalc.Core.Entities.FilamentType", "FilamentType")
                        .WithMany("StockMovements")
                        .HasForeignKey("FilamentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilamentStock");

                    b.Navigation("FilamentType");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Customer", b =>
                {
                    b.Navigation("Calculations");

                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.FilamentType", b =>
                {
                    b.Navigation("PrinterLinks");

                    b.Navigation("StockMovements");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Printer", b =>
                {
                    b.Navigation("Calculations");

                    b.Navigation("SupportedFilaments");
                });

            modelBuilder.Entity("PrintCalc.Core.Entities.Quote", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
